version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-atlas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-atlas}
    volumes:
      - ./db-data/postgres:/var/lib/postgresql/data
    networks:
      - atlas-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  atlas-web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    #env_file:
     # - .env
    networks:
      - atlas-net

networks:
  atlas-net:
    driver: bridge
